name: Bug 反馈
description: 提交一个 Bug 报告
title: "[Bug]: "
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        感谢您反馈 Bug！在提交之前，请先说明 Bug 发生时的情况：

  - type: input
    id: plugin-name
    attributes:
      label: 使用的插件名称
      placeholder: 例如：koishi-plugin-example
    validations:
      required: true

  - type: input
    id: plugin-version
    attributes:
      label: 插件的版本号
      placeholder: 例如：v1.2.3
    validations:
      required: true

  - type: textarea
    id: koishi-webui-env
    attributes:
      label: `koishi webUI` 的环境信息
      description: 如果在 `koishi webUI` 中遇到问题，请提供环境信息 (浏览器版本、操作系统等)
      placeholder: 例如：Chrome 114.0.5735.198, Windows 10
    validations:
      required: false

  - type: textarea
    id: koishi-webui-deps
    attributes:
      label: `koishi webUI` 的依赖列表
      description: 如果在 `koishi webUI` 中遇到问题，请提供 `koishi webUI` 的依赖列表 (可以在 `koishi webUI` 控制台中查看)
      placeholder: 请粘贴依赖列表
    validations:
      required: false

  - type: input
    id: koishi-adapter-protocol
    attributes:
      label: 使用的 Koishi 适配器或协议
      placeholder: 例如：onebot, discord, console
    validations:
      required: true

  - type: textarea
    id: describe-bug
    attributes:
      label: 请详细描述你遇到的 Bug *
      description: 尽可能详细地描述 Bug 的现象、触发步骤、预期行为和实际行为。
      placeholder: 我在使用 XXX 功能时，遇到了 XXX 问题...
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: 复现步骤
      description: 请提供清晰的复现步骤，方便我们重现问题。
      placeholder: 1. 打开 XXX 功能\n2. 点击 XXX 按钮\n3. 出现错误...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: 预期行为
      description: 你期望发生什么？
      placeholder: 我期望点击按钮后应该...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: 实际行为
      description: 实际发生了什么？
      placeholder: 实际上点击按钮后却...
    validations:
      required: true

  - type: textarea
    id: error-log
    attributes:
      label: 完整的报错日志
      description: 如果有报错信息，请提供完整的报错日志。
      placeholder: 请粘贴完整的报错日志
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: 截图
      description: 如果可以，请提供 Bug 的截图，这有助于我们更好地理解问题。
      placeholder: 请将截图粘贴或拖拽到这里
    validations:
      required: false

  - type: checkboxes
    id: check-list
    attributes:
      label: 检查清单
      description: 提交前请检查以下事项
      options:
        - label: 我已经填写了插件名称和版本号
        - label: 我已经详细描述了 Bug 现象和复现步骤
        - label: 我已经提供了完整的报错日志 (如果有)
        - label: 我已经尽可能提供了足够的信息来重现问题
