name: 功能增改请求 (Feature Request)
description: 提交一个关于 koishi-shangxue-app 插件的功能增改请求
title: "[Feature]: "
labels: ["feature"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        感谢您提出功能增改请求！请尽可能详细地描述您希望添加或修改的功能。

  - type: input
    id: plugin-name
    attributes:
      label: 需要增改的插件名称
      description: 请提供您希望增改功能的插件名称
      placeholder: 例如：koishi-plugin-example
    validations:
      required: true

  - type: textarea
    id: feature-description
    attributes:
      label: 详细描述你想要的功能
      description: 请详细描述你希望添加或修改的功能，包括它的用途、目标用户、以及解决什么问题。
      placeholder: 我希望添加一个 XXX 功能，它可以帮助用户...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: 可能的解决方案 (可选)
      description: 如果您有任何关于如何实现这个功能的想法，请在这里描述。
      placeholder: 我认为可以通过 XXX 技术来实现...
    validations:
      required: false

  - type: textarea
    id: alternatives-considered
    attributes:
      label: 考虑过的替代方案 (可选)
      description: 已经考虑过了的方案，但效果不好，且使用上述方案解决会更优秀。
      placeholder: 我也考虑过 XXX 方案，但...缺点...，如果采用上述方案...
    validations:
      required: false

  - type: checkboxes
    id: check-list
    attributes:
      label: 检查清单
      description: 提交前请检查以下事项
      options:
        - label: 我已经确认这是针对 koishi-shangxue-app 插件的功能请求。
        - label: 我已经搜索了已有的 Issue，确认没有重复的功能请求。
        - label: 我已经尽可能详细地描述了功能的需求和用途。

