name: Bug Report  # 模板名称，用户看到的
description: 提交一个 Bug 报告  # 模板描述，用户看到的
title: "[Bug]: "  # Issue 标题的默认前缀，用户可以修改
labels: ["bug"]  # 自动添加的标签
assignees: [] # 默认的指派人，可以留空

body:
  - type: markdown
    attributes:
      value: |
        感谢您提交 Bug 报告！在提交之前，请确保您已经：
        - 仔细阅读了文档
        - 搜索了已有的 Issue，确认没有重复的 Bug 报告

  - type: input
    id: version
    attributes:
      label: 你使用的 Koishi Shangxue Apps 版本是什么？
      description: 请提供你正在使用的 Koishi Shangxue Apps 的版本号，例如 v1.2.3
      placeholder: v1.2.3
    validations:
      required: true

  - type: input
    id: koishi-version
    attributes:
      label: 你使用的 Koishi 版本是什么？
      description: 请提供你正在使用的 Koishi 主框架的版本号，例如 v4.15.0
      placeholder: v4.15.0
    validations:
      required: true

  - type: textarea
    id: describe-bug
    attributes:
      label: 请详细描述你遇到的 Bug
      description: 尽可能详细地描述 Bug 的现象、触发步骤、预期行为和实际行为。
      placeholder: 我在使用 XXX 功能时，遇到了 XXX 问题...
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: 复现步骤
      description: 请提供清晰的复现步骤，方便我们重现问题。
      placeholder: 1. 打开 XXX 功能\n2. 点击 XXX 按钮\n3. 出现错误...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: 预期行为
      description: 你期望发生什么？
      placeholder: 我期望点击按钮后应该...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: 实际行为
      description: 实际发生了什么？
      placeholder: 实际上点击按钮后却...
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: 截图 (可选)
      description: 如果可以，请提供 Bug 的截图，这有助于我们更好地理解问题。
      placeholder: 请将截图粘贴或拖拽到这里
    validations:
      required: false

  - type: checkboxes
    id: check-list
    attributes:
      label: 检查清单
      description: 提交前请检查以下事项
      options:
        - label: 我已经仔细阅读了文档
        - label: 我已经搜索了已有的 Issue，确认没有重复的 Bug 报告
        - label: 我已经提供了足够的信息来重现问题
