name: Deploy VitePress Docs to GitHub Pages

on:
  push:
    branches:
      - main  # 在 main 分支推送时触发
    paths:
      - 'docs/**' # 仅在 docs 目录下的文件发生更改时触发
  workflow_dispatch:  # 允许手动触发

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main  # 检出 main 分支
          path: main  # 检出到 main 目录

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn' # 使用 yarn 缓存

      - name: Install Dependencies
        run: yarn install --cwd main # 指定 yarn.lock 文件的位置

      - name: Build VitePress Site
        run: yarn build --cwd main

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
          clean: false # 保留 gh-pages 分支的内容

      - name: Copy build output to gh-pages
        run: |
          rm -rf gh-pages/docs/*  # 清空 gh-pages/docs 目录
          cp -r main/docs/.vitepress/dist/* gh-pages/docs/  # 复制构建输出

      - name: Commit and push changes to gh-pages
        run: |
          cd gh-pages
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Deploy VitePress site to gh-pages" || echo "No changes to commit"
          git push origin gh-pages

