name: ci

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"  # 每小时执行一次

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Auto green
        run: |
          git config --local user.email "1919892171@qq.com"
          git config --local user.name "shangxueink"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "A commit an hour, a green square acquired."
          git push
