name: QQNT-version-scraper

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  scrape_and_update_versionlist:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码 ⬇️
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 设置 Node.js ⚙️
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: 安装依赖 📦
        run: npm install cheerio

      - name: 显示当前工作目录 📂 (Debug)
        run: pwd

      - name: 列出 scripts/QQNT-version-scraper 目录内容 📂 (Debug)
        run: ls -l ./scripts/QQNT-version-scraper/

      - name: 创建 QQNT 目录 📂 (Debug mkdir)
        run: |
          mkdir -p ./scripts/QQNT-version-scraper/QQNT
          echo "目录创建命令执行完毕"
          ls -l ./scripts/QQNT-version-scraper/ # 再次列出目录内容，确认创建结果

      - name: 运行版本抓取脚本 🚀
        run: node ./scripts/QQNT-version-scraper/index.js

      - name: 检查版本更新 🔍
        id: check_update
        run: |
          UPDATED=false
          for platform in windows linux mac; do
            if [[ -f ./scripts/QQNT-version-scraper/QQNT/${platform}-versionlist.json ]]; then
              NEW_VERSION_LIST=$(cat ./scripts/QQNT-version-scraper/QQNT/${platform}-versionlist.json)
              OLD_VERSION_LIST=$(git show origin/main:./scripts/QQNT-version-scraper/QQNT/${platform}-versionlist.json)

              if [[ "$NEW_VERSION_LIST" != "$OLD_VERSION_LIST" ]]; then
                echo "检测到 ${platform} 版本更新！"
                UPDATED=true
              fi
            else
              echo "未找到 ${platform}-versionlist.json，首次运行，将更新。"
              UPDATED=true
            fi
          done
          if [[ "$UPDATED" == "true" ]]; then
            echo "updated=true" >> "$GITHUB_OUTPUT"
          else
            echo "版本没有更新，跳过提交。"
            echo "updated=false" >> "$GITHUB_OUTPUT"
          fi

      - name: 提交版本文件 ➕
        if: steps.check_update.outputs.updated == 'true'
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add ./scripts/QQNT-version-scraper/QQNT/*-versionlist.json ./scripts/QQNT-version-scraper/QQNT/*-versionlist.md
          git commit -m "✨ 更新 QQNT 版本列表信息"
          git push
